import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.scss";
import { GlobalProvider } from "@/context/GlobalContext";

const font = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={`bg-neutral-950 ${font.className}`}>{children}</body>
      </html>
    </GlobalProvider>
  );
}
